[General]
codepage=65001
AutoKeyboardSwitching=T
DialogFontsize=18
LowerCaseLetters=abcdeɛfghiɩjklmnoɔpqrstuʋvwxyz
NoCaseLetters=
RTL=F
UpperCaseLetters=ABCDEƐFGHIƖJKLMNOƆPQRSTUƲVWXYZ
errors=
font=Doulos SIL
name=GhanaUnicode
separator=/
size=18

[Checking]

[Characters]
Chr01=a/A
Chr02=á Á
Chr03=b/B
Chr04=c/C
Chr05=d/D
Chr06=e/E
Chr07=é É
Chr08=ɛ/Ɛ
Chr09=ɛ́ Ɛ́
Chr10=f/F
Chr11=g/G
Chr12=h/H
Chr13=i/I
Chr14=í Í
Chr15=ɩ/Ɩ
Chr16=ɩ́ Ɩ́
Chr17=j/J
Chr18=k/K
Chr19=l/L
Chr20=m/M
Chr21=n/N
Chr22=ŋ/Ŋ
Chr23=o/O
Chr24=ó Ó
Chr25=ɔ/Ɔ
Chr26=ɔ́ Ɔ́
Chr27=p/P
Chr28=q/Q
Chr29=r/R
Chr30=s/S
Chr31=t/T
Chr32=u/U
Chr33=ú Ú
Chr34=ʋ/Ʋ
Chr35=ʋ́ Ʋ́
Chr36=v/V
Chr37=w/W
Chr38=x/X
Chr39=y/Y
Chr40=z/Z

[Punctuation]
diacritics=́
diacriticsfollow=Yes
footnotes=
medial=- -- *
