cd %SVN_DIR%\XeLaTexConvert\XeLaTexExe\texmf-dist\tex\generic\hyph-utf8\patterns\txt
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-zh-latn-pinyin.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-uk.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-tr.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-tk.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-te.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-as.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-ta.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-sv.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-sl.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-bg.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-sa.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-ro.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-pa.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-bn.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-or.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-mul-ethi.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-mr.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-mn-cyrl.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-ml.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-lv.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-lt.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-cop.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-lo.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-la.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-kn.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-kmr.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-it.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-is.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-hy.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-cy.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-hu.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-hr.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-hi.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-da.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-gu.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-grc.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-gl.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-de-1901.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-fr.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-fi.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-eu.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-de-1996.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-et.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-es.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-eo.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-de-ch-1901.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-el-polyton.hyp.txt /y
xcopy %SVN_DIR%\XeLaTexConvert\empty-hyph.txt hyph-el-monoton.hyp.txt /y
