TEXMFVAR $TEXMFSYSVAR
binary_win32 1
collection-basic 1
collection-langenglish 1
in_place 0
option_autobackup 1
option_backupdir tlpkg/backups
option_desktop_integration 0
option_doc 0
option_file_assocs 0
option_fmt 1
option_letter 1
option_path 0
option_post_code 1
option_src 0
option_sys_bin /usr/local/bin
option_sys_info /usr/local/info
option_sys_man /usr/local/man
option_w32_multi_user 0
option_write18_restricted 1
portable 1
