<?xml version="1.0" encoding="UTF-8"?>
<!-- Copies over the punctuation elements into the xhtml itself -->
<!-- NOTE: the opening and closing punctuation templates are generated by Pathway code.  -->

<xsl:transform version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    exclude-result-prefixes="xhtml">

	<xsl:output method="xml" version="1.0" encoding="UTF-8" doctype-public="-//W3C//DTD XHTML 1.1//EN" doctype-system="http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd" indent="yes"/>
	<xsl:strip-space elements="*"/>
	
	<!--Straight copy for these elements. -->
	<xsl:template match="xhtml:html | xhtml:body | xhtml:head | xhtml:meta | xhtml:title | xhtml:link | xhtml:a | xhtml:table | xhtml:tr | xhtml:td | xhtml:em | xhtml:br | xhtml:ol | xhtml:ul | xhtml:img | xhtml:h1 | xhtml:p | xhtml:h2 | xhtml:h3 | xhtml:div | xhtml:li">
		<xsl:copy>
			<xsl:for-each select="@*">
				<xsl:copy/>
			</xsl:for-each>
			<xsl:apply-templates/>
		</xsl:copy>
	</xsl:template>

	<!-- span processing -->  
	<xsl:template match="xhtml:span">
		<xsl:if test="count(child::*) > 0 or string-length(normalize-space(./text())) > 0">
			<xsl:copy>
				<xsl:for-each select="@*">
					<xsl:copy/>
				</xsl:for-each>
				<!-- OPENING lexical punctuation -->
				<!-- lexical element itself -->
				<xsl:apply-templates/>
				<!-- CLOSING lexical punctuation -->
			</xsl:copy>
		</xsl:if>
	</xsl:template>

	<!-- Special handling of text. -->
	<xsl:template match="text()">
		<xsl:if test="not(ancestor::xhtml:div[@class='Title_Main']/xhtml:span[not(@class)])">
			<!-- Replace curly quotes with straight quotes. -->
			<xsl:value-of select="translate(.,'“”','&quot;&quot;')"/>
		</xsl:if>
	</xsl:template>
	
	<!-- Default element and attribute templates. -->
	<xsl:template match="*">
		<xsl:comment>Warning :: The element "<xsl:value-of select="name()"/>", child of "<xsl:value-of select="name(..)"/>", has no matching template.</xsl:comment>
	</xsl:template>
	<!-- default attribute template -->
	<xsl:template match="@*">
		<xsl:comment>Warning :: The attribute "<xsl:value-of select="name()"/>" for element "<xsl:value-of select="name(..)"/>" has no matching template.</xsl:comment>
	</xsl:template>

</xsl:transform>