#!/bin/sh
# sort a file in Cyrillic koi8-r encoding alphabetically
#
# -f Fold lower case characters into the equivalent upper case
#    characters when sorting so that, for example, `B' is greater
#    than `a' (without `-f', uppercase characters precede lowercase).

if [ "$1" = "-f" ]; then
	FOLD="-f"
	ALPH='^^e1^^c1^^e2^^c2^^f7^^d7^^e7^^c7^^e4^^c4^^e5^^c5^^b3^^a3^^f6^^d6^^fa^^da^^e9^^c9^^ea^^ca^^eb^^cb^^ec^^cc^^ed^^cd^^ee^^ce^^ef^^cf^^f0^^d0^^f2^^d2^^f3^^d3^^f4^^d4^^f5^^d5^^e6^^c6^^e8^^c8^^e3^^c3^^fe^^de^^fb^^db^^fd^^dd^^ff^^df^^f9^^d9^^f8^^d8^^fc^^dc^^e0^^c0^^f1^^d1'
else
	ALPH='^^e1^^e2^^f7^^e7^^e4^^e5^^b3^^f6^^fa^^e9^^ea^^eb^^ec^^ed^^ee^^ef^^f0^^f2^^f3^^f4^^f5^^e6^^e8^^e3^^fe^^fb^^fd^^ff^^f9^^f8^^fc^^e0^^f1^^c1^^c2^^d7^^c7^^c4^^c5^^a3^^d6^^da^^c9^^ca^^cb^^cc^^cd^^ce^^cf^^d0^^d2^^d3^^d4^^d5^^c6^^c8^^c3^^de^^db^^dd^^df^^d9^^d8^^dc^^c0^^d1'
fi
TEMP='^^be^^bf^^c0^^c1^^c2^^c3^^c4^^c5^^c6^^c7^^c8^^c9^^ca^^cb^^cc^^cd^^ce^^cf^^d0^^d1^^d2^^d3^^d4^^d5^^d6^^d7^^d8^^d9^^da^^db^^dc^^dd^^de^^df^^e0^^e1^^e2^^e3^^e4^^e5^^e6^^e7^^e8^^e9^^ea^^eb^^ec^^ed^^ee^^ef^^f0^^f1^^f2^^f3^^f4^^f5^^f6^^f7^^f8^^f9^^fa^^fb^^fc^^fd^^fe^^ff'

tr $ALPH $TEMP | sort $FOLD | tr $TEMP $ALPH
